Update to 4.2 but still compatible with 4.1
payplug/payplug-orocommerce pull request #24
Opened 2021-03-16 14:39 UTC by startupz

2021-03-16 14:51 UTC, dan-payplug requested changes

2021-03-16 14:51 UTC, dan-payplug commented on composer.json
> +        "oro/commerce": "4.1.* || 4.2.*"
```suggestion
        "oro/commerce": "^4.1.*"
```

2021-03-16 14:51 UTC, dan-payplug commented on composer.json
> +        "oro/commerce": "4.1.* || 4.2.*"
C'est possible non ?

2021-03-16 15:23 UTC, dan-payplug approved these changes

2021-03-16 15:23 UTC, merged

2021-04-29 08:50 UTC, Dnd-Smash commented
Hello,

Do you have an estimation for the release date for this update by any chance ?

Many thanks,

2021-04-29 09:28 UTC, dan-payplug commented
Hello @Dnd-Smash,

We will submit our new version today so it will be available probably during next week depending of Orocommerce reviewing process.

Thank you :)